#!/bin/bash
# Ubuntu to MacOS Converter
# 2020 
# George Tsarouxas
# tsarouxas@hellenictechnologies.com

macos_version="light"
response = ""
echo -e "Please choose the version for your MacOS (default is light)\n\n1) light\n2) dark\n\nEnter your selection: "
read response
if [ "$response" == "dark" ] || [ $response == 2 ]; then
    macos_version="dark"
fi
echo $macos_version
#exit 1



#Prerequisites
echo 'Installing Prerequisites';
sudo add-apt-repository universe
sudo apt install gnome-tweak-tool
sudo apt install gnome-shell-extensions
sudo apt install dconf-editor
sudo apt-get install autokey-gtk
sudo apt install curl
sudo apt install wget
#FONTS
echo 'Installing Fonts';
curl mac-fonts.zip https://drive.noobslab.com/data/Mac/macfonts.zip  &&
sudo unzip mac-fonts.zip -d /usr/share/fonts; rm mac-fonts.zip
curl -kL https://raw.github.com/cstrap/monaco-font/master/install-font-ubuntu.sh | bash
sudo apt-get install msttcorefonts
sudo fc-cache -f -v

#VIBER
echo 'Installing VIBER';
curl -OL https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb &&
sudo apt install gdebi-core &&
curl -OL http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.3_amd64.deb &&
sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu5.3_amd64.deb &&
sudo gdebi ~/viber.deb
#Flameshot - Screenshots with Area
echo 'Installing Flameshot';
sudo apt install flameshot

#Install the MacOS Theme
if [ "$macos_version" == "dark" ]; then
    echo 'Installing Dark MacOS Theme';
    sudo cp ./assets/icons/Cameo-Dark-OSX /usr/share/themes/  &&
    gsettings set org.gnome.desktop.interface gtk-theme 'Cameo-Dark-OSX'
else
    echo 'Installing Light MacOS Theme';
    sudo cp ./assets/icons/Cameo-OSX /usr/share/themes/  &&
    gsettings set org.gnome.desktop.interface gtk-theme 'Cameo-OSX'
fi

#Install the MacOS Icons
echo 'Installing the MacOS Icons';
sudo cp ./assets/icons/Os-Catalina-icons /usr/share/icons/ &&
gsettings set org.gnome.desktop.interface icon-theme 'Os-Catalina-icons'

#Install the MacOS Shell

#Install Dropbox
curl -OL https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb
sudo apt install python3-gpg; 
sudo apt install ./dropbox_2020.03.04_amd64.deb

#Set window top bar buttons to the left
gsettings set org.gnome.desktop.wm.preferences button-layout ',close,minimize,maximize:'

#Dock to Center and bottom
gsettings set org.gnome.shell.extensions.dash-to-dock extend-height false 
gsettings set org.gnome.shell.extensions.dash-to-dock dock-position BOTTOM 
gsettings set org.gnome.shell.extensions.dash-to-dock transparency-mode FIXED 
gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 64 
gsettings set org.gnome.shell.extensions.dash-to-dock unity-backlit-items true
gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 32
gsettings set org.gnome.shell.extensions.dash-to-dock unity-backlit-items false

#Set the Mac Fonts
gsettings reset org.gnome.desktop.interface text-scaling-factor
gsettings set org.gnome.desktop.interface font-name 'Lucida MAC Normal 9'
gsettings set org.gnome.desktop.interface document-font-name 'Lucida MAC Normal 11'
gsettings set org.gnome.desktop.interface monospace-font-name 'Andale Mono Bold 9'
gsettings set org.gnome.nautilus.desktop font 'Lucida MAC Normal 8'

#Terminal Keyboard Shortcuts
gsettings set org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ new-tab '<Ctrl>t'
gsettings set org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ close-tab '<Ctrl>w'
gsettings set org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ new-window '<Shift><Ctrl>t'
gsettings set org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ close-window '<Ctrl>n'
gsettings set org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ copy '<Ctrl>c'
gsettings set org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ paste '<Ctrl>v'
gsettings set org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ select-all '<Ctrl>a'

#Keyboard Shortcuts
gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Ctrl>Tab']"
gsettings set org.gnome.desktop.wm.keybindings launch-terminal "['<Shift><Ctrl>Tab']"
gsettings set org.gnome.desktop.wm.keybindings lock-screen "['<Ctrl><Super>q']"
#TODO: gsettings set org.gnome.desktop.wm.keybindings show-all-applications "['<Alt><Space>']"


#LocalWP
echo 'Installing LocalWP';
curl -OL https://cdn.localwp.com/stable/latest/deb
sudo dpkg -i local*linux.deb

#VS Code
wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
sudo apt install code

#Install Teamviewer
sudo apt install teamviewer